services:

  vignesh-ui:
    volumes:
      - d:/code/vignesh/:/app
    ports:
      - 3000:3000
    build:
      context: ./
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
  